using AOC2022;
Console.WriteLine("Day 1");
Day1.Start();
Console.WriteLine();
Console.WriteLine("Day 2");
Day2.Start();
Console.WriteLine();
Console.WriteLine("Day 3");
Day3.Start();
Console.WriteLine();
Console.WriteLine("Day 4");
Day4.Start();
Console.WriteLine();
Console.WriteLine("Day 5");
Day5.Start();
Console.WriteLine();
Console.WriteLine("Day 6");
Day6.Start();
Console.WriteLine();
Console.WriteLine("Day 7");
Day7.Start();
Console.WriteLine();
Console.WriteLine("Day 8");
Day8.Start();
Console.WriteLine();
Console.WriteLine("Day 9");
Day9.Start();
Console.WriteLine();
Console.WriteLine("Day 10");
Day10.Start();
Console.WriteLine();
Console.WriteLine("Day 11");
Day11.Start();
Console.WriteLine();
Console.WriteLine("Day 12");
Day12.Start();
Console.WriteLine();
Console.WriteLine("Day 13");
Day13.Start();
Console.WriteLine();
Console.WriteLine("Day 14");
Day14.Start();
Console.WriteLine();
Console.WriteLine("Day 15");
Day15.Start();
Console.WriteLine();
Console.WriteLine("Day 16");
Day16.Start();
Console.WriteLine();
Console.WriteLine("Day 17");
Day17.Start();
Console.WriteLine();
Console.WriteLine("Day 18");
Day18.Start();
Console.WriteLine();
Console.WriteLine("Day 19");
Day19.Start();
Console.WriteLine();
Console.WriteLine("Day 20");
Day20.Start();
Console.WriteLine();
Console.WriteLine("Day 21");
Day21.Start();
Console.WriteLine();
Console.WriteLine("Day 22");
Day22.Start();
Console.WriteLine();
Console.WriteLine("Day 23");
Day23.Start();
Console.WriteLine();
Console.WriteLine("Day 24");
Day24.Start();
Console.WriteLine();
Console.WriteLine("Day 25");
Day25.Start();
Console.WriteLine();